# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Richa Singh Madnawat
title: Data Scientist
email: singhricha2995@gmail.com
phone: +1 519 694 8522

# Social links
github_username: singhricha2995
twitter_username: singhricha2995
linkedin_username: singhricha2995

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an experienced Junior Production Engineer in the field of Manufacturing, also skilled in Data Science techniques i.e. Data Wrangling, Data Mining, Data Analysis, and generating Business Insights for top level management. Always inquisitive about knowing how any kind of Data can influence a business on a whole.  
  Skills: <mark>Python</mark>, <mark>SQL</mark>, <mark>Tableau</mark> and <mark>PowerBI</mark>
# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Professional Certifications (In Progress)
more_content: | # this will include new lines to allow paragraphs
   - [Practical Data Science with MATLAB Specialization](https://www.coursera.org/specializations/practical-data-science-matlab) (MathWorks)
   - [Data Mining Specialization](https://www.coursera.org/specializations/data-mining) (University of Illinois at Urbana-Champaign)
   - [Data Science Professional Certificate](https://www.coursera.org/professional-certificates/ibm-data-science) (IBM)
   - [Applied AI Professional Certificate](https://www.coursera.org/professional-certificates/applied-artifical-intelligence-ibm-watson-ai) (IBM)
   - PLC SCADA and MATLAB (Sofcon Systems India Private Limited)
   - Embedded Systems (Drmz System Innovations Pvt Ltd)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
